# https://docs.netlify.com/configure-builds/file-based-configuration/
[build]
command = "pnpm build"
publish = "packages/cart/build"
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
[template.environment]
PUBLIC_SELF_HOSTED_SLUG = "fairtouch"
